services:
    # Path resolvers
    pb_sulu_storage.local.path_resolver:
        class: PB\Bundle\SuluStorageBundle\Resolver\LocalPathResolver
        tags:
            - { name: pb_sulu_storage.path_resolver, alias: local }

    pb_sulu_storage.s3.path_resolver:
        class: PB\Bundle\SuluStorageBundle\Resolver\AwsS3v3PathResolver
        tags:
            - { name: pb_sulu_storage.path_resolver, alias: awss3v3 }

    # URL resolvers
    pb_sulu_storage.local.url_resolver:
        class: PB\Bundle\SuluStorageBundle\Resolver\LocalUrlResolver
        arguments: ['%kernel.root_dir%/../web']
        tags:
            - { name: pb_sulu_storage.url_resolver, alias: local }

    pb_sulu_storage.s3.url_resolver:
        class: PB\Bundle\SuluStorageBundle\Resolver\AwsS3v3UrlResolver
        tags:
            - { name: pb_sulu_storage.url_resolver, alias: awss3v3 }